AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Marstonstone Backend Services managed by AWS SAM

Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Runtime: nodejs16.x

  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"

Parameters:
  DeployEnvironment:
    Type: String
    Description: 'Environment of deployment (dev/prod)'

Resources:
  # Lambda Functions
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - 'HelloWorld-${env}'
        - env: !Ref DeployEnvironment
      CodeUri: src/functions/hello-world/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrderTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  # # APIs
  # InternalAPI:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: !Ref DeployEnvironment
  # Auth:
  #   # DefaultAuthorizer: CognitoAuthorizer
  #   Authorizers:
  #     CognitoAuthorizer:
  #       UserPoolArn: !Sub
  #         - 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'
  #         - UserPoolId: !FindInMap [Cognito, UserPoolId, !Ref DeployEnvironment]

  # DynamoDB Tables
  BuilderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'builder-${env}'
        - env: !Ref DeployEnvironment
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'customer-${env}'
        - env: !Ref DeployEnvironment
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: builder
          AttributeType: S
        - AttributeName: staff
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: builder-staff
          KeySchema:
            - AttributeName: builder
              KeyType: HASH
            - AttributeName: staff
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10

  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'order-${env}'
        - env: !Ref DeployEnvironment
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: builder
          AttributeType: S
        - AttributeName: staff
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: builder-staff
          KeySchema:
            - AttributeName: builder
              KeyType: HASH
            - AttributeName: staff
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10

  SupplierTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'supplier-${env}'
        - env: !Ref DeployEnvironment
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  MaterialTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'material-${env}'
        - env: !Ref DeployEnvironment
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: supplier
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: builder-staff
          KeySchema:
            - AttributeName: supplier
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10

  # Cognito User Pools
  StaffUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub
        - 'StaffPool-${env}'
        - env: !Ref DeployEnvironment
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
          TemporaryPasswordValidityDays: 7

  # Cognito User Pool Clients
  StaffUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref StaffUserPool
      GenerateSecret: false

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
  #   Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
  BuilderTable:
    Description: 'DynamoDB Builder Table'
    Value: !Ref BuilderTable

  CustomerTable:
    Description: 'DynamoDB Customer Table'
    Value: !Ref CustomerTable

  OrderTable:
    Description: 'DynamoDB Order Table'
    Value: !Ref OrderTable

  SupplierTable:
    Description: 'DynamoDB Supplier Table'
    Value: !Ref SupplierTable

  MaterialTable:
    Description: 'DynamoDB Material Table'
    Value: !Ref MaterialTable

  StaffUserPool:
    Description: 'Staff UserPool Id'
    Value: !Ref StaffUserPool

  StaffUserPoolClient:
    Description: 'Staff UserPool Client Id'
    Value: !Ref StaffUserPoolClient
